files = Split("""
	bgbg.c
	components.c
	exec.c
	fileform.c
	Main.c
	plugin.c
	Ui.c
	util.c
	#Source/crc32.c
""")

files_7z = Split("""
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/BenchCon.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/ConsoleClose.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/ExtractCallbackConsole.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/HashCon.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/List.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/Main6.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/MainAr.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/OpenCallbackConsole.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/PercentPrinter.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/UpdateCallbackConsole.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Console/UserInputUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Bundles/Alone/StdAfx.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/CommandLineParser.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/CRC.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/CrcReg.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/IntToString.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/ListFileUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/MyString.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/MyVector.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/NewHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/Sha1Reg.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/Sha256Reg.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/StdInStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/StdOutStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/StringConvert.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/StringToInt.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/UTFConvert.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/Wildcard.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/XzCrc64Init.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Common/XzCrc64Reg.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/DLL.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/ErrorMsg.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/FileDir.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/FileFind.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/FileIO.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/FileLink.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/FileName.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/FileSystem.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/MemoryLock.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/PropVariant.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/PropVariantConv.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/PropVariantUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/Synchronization.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/System.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/Windows/TimeUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/CreateCoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/CWrappers.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/FilePathAutoRename.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/FileStreams.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/FilterCoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/InBuffer.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/InOutTempBuffer.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/LimitedStreams.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/LockedStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/MemBlocks.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/MethodId.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/MethodProps.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/OffsetStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/OutBuffer.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/OutMemStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/ProgressMt.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/ProgressUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/PropId.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/StreamBinder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/StreamObjects.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/StreamUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/UniqBlocks.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Common/VirtThread.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BZip2Crc.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BZip2Decoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BZip2Encoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BZip2Register.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/CopyCoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/CopyRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/Deflate64Register.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/DeflateDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/DeflateEncoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/DeflateRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/ImplodeDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/Lzma2Decoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/Lzma2Encoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/Lzma2Register.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/LzmaDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/LzmaEncoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/LzmaRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/PpmdDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/PpmdEncoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/PpmdRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/PpmdZip.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/ShrinkDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/LzxDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/QuantumDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/Bcj2Coder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/Bcj2Register.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BcjCoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BcjRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BitlDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BranchMisc.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/BranchRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/ByteSwap.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/DeltaFilter.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/LzOutWindow.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/XzDecoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Compress/XzEncoder.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zCompressionMode.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zDecode.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zEncode.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zExtract.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zFolderInStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zHandlerOut.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zHeader.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zIn.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zOut.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zProperties.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zSpecStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/7z/7zUpdate.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Tar/TarHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Tar/TarHandlerOut.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Tar/TarHeader.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Tar/TarIn.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Tar/TarOut.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Tar/TarRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Tar/TarUpdate.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipAddCommon.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipHandlerOut.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipIn.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipItem.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipOut.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Zip/ZipUpdate.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/CoderMixer2.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/DummyOutStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/FindSignature.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/HandlerOut.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/InStreamWithCRC.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/ItemNameUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/MultiStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/OutStreamWithCRC.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Common/ParseProperties.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Cab/CabBlockInStream.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Cab/CabHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Cab/CabHeader.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Cab/CabIn.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Cab/CabRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/Bz2Handler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/DeflateProps.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/GzHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/LzmaHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/SplitHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Archive/XzHandler.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/ArchiveCommandLine.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/ArchiveExtractCallback.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/ArchiveOpenCallback.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/Bench.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/DefaultName.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/EnumDirItems.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/Extract.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/ExtractingFilePath.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/HashCalc.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/LoadCodecs.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/OpenArchive.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/PropIDUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/SetProperties.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/SortUtils.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/TempFiles.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/Update.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/UpdateAction.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/UpdateCallback.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/UpdatePair.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/Common/UpdateProduce.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/7zAes.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/7zAesRegister.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/HmacSha1.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/MyAes.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/MyAesReg.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/Pbkdf2HmacSha1.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/RandGen.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/WzAes.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/ZipCrypto.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/Crypto/ZipStrong.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Xz.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/XzCrc64.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/XzCrc64Opt.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/XzDec.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/XzEnc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/XzIn.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/7zCrc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/7zCrcOpt.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/7zStream.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Aes.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/AesOpt.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Alloc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Bcj2.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Bcj2Enc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Bra.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Bra86.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/BraIA64.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/BwtSort.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/CpuArch.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Delta.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/DllSecur.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/HuffEnc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/LzFind.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/LzFindMt.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Lzma2Dec.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Lzma2DecMt.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Lzma2Enc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/LzmaDec.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/LzmaEnc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/MtCoder.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/MtDec.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Ppmd7.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Ppmd7Dec.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Ppmd7Enc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Ppmd8.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Ppmd8Dec.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Ppmd8Enc.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Sha1.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Sha256.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Sort.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/C/Threads.c
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/NSIS/Extract7z.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/NSIS/ExtractCallbackConsoleNsis7z.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/NSIS/MainArNsis7z.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/NSIS/MainNsis7z.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/NSIS/NSISBreak.cpp
	#Source/../Contrib/7-Zip/Contrib/nsis7z/CPP/7zip/UI/NSIS/UserInputUtils2.cpp
""")

files = files + files_7z

resources = Split("""
	resource.rc
""")

resource_files = Split("""
	nsis.ico
	uninst.ico
	bitmap1.bmp
""")

bzip2_files = Split("""
	#Source/bzip2/bzlib.c
	#Source/bzip2/decompress.c
	#Source/bzip2/huffman.c
""")

lzma_files = Split("""
	#Source/7zip/LZMADecode.c
""")

zlib_files = Split("""
	#Source/zlib/INFBLOCK.C
""")

libs = Split("""
	advapi32
	shell32
	ole32
	comdlg32
	comctl32
	user32
	gdi32
	kernel32
	uuid
	oleaut32
""")

Import('env compression solid_compression')

### Defines

env.Append(CPPDEFINES = ['EXEHEAD'])
env.Append(CPPDEFINES = ['WIN32_LEAN_AND_MEAN'])
env.Append(CPPDEFINES = ['_WIN32_IE=0x0500'])

### Some other settings

if 'NSIS_CONFIG_LOG_STDOUT' in env['NSIS_CPPDEFINES']:
	env.Append(LINKFLAGS = env['SUBSYS_CON'])
else:
	env.Append(LINKFLAGS = env['SUBSYS_WIN'])

### Compression specific configuration

if compression == 'bzip2':
	env.Append(CPPDEFINES = ['NSIS_COMPRESS_USE_BZIP2'])
	files += bzip2_files
elif compression == 'lzma':
	env.Append(CPPDEFINES = ['NSIS_COMPRESS_USE_LZMA'])
	env.Append(CPPDEFINES = ['LZMACALL=__fastcall'])
	files += lzma_files
elif compression == 'zlib':
	env.Append(CPPDEFINES = ['NSIS_COMPRESS_USE_ZLIB'])
	env.Append(CPPDEFINES = ['ZEXPORT=__stdcall'])
	files += zlib_files

if solid_compression:
	env.Append(CPPDEFINES = ['NSIS_COMPRESS_WHOLE'])

### Build with no sub-build-directories

objs = []

def basename(file):
	return file.split('/')[-1].split('.')[0]

for file in files:
	objs.append(env.Object(target = basename(file), source = file))

### Resources

res = env.RES(resources)
env.Depends(res, resource_files)
objs = objs + res

### Build stub

stub = env.Program(target = 'stub_' + compression, source = objs, LIBS = libs)

### Return stub

Return('stub')
